"""Curated static data for One Smart PWA."""
from datetime import datetime, timezone, timedelta

# ============ SCHOLARSHIPS ============
# age_max = maximum age accepted (None = no upper limit)
SCHOLARSHIPS = [
    {
        "id": "chevening",
        "name": "Chevening Scholarship",
        "country": "United Kingdom",
        "country_code": "GB",
        "degree": "S2",
        "deadline": "2026-10-07",
        "age_min": 21,
        "age_max": None,
        "benefits": [
            "Tuition fees fully covered",
            "Monthly living stipend (~£1,500)",
            "Return economy flights",
            "Visa application costs",
            "Arrival allowance and thesis grant",
        ],
        "requirements": [
            "Warga negara Indonesia (atau negara yang eligible)",
            "Minimal 2 tahun pengalaman kerja (2,800 jam)",
            "Gelar S1 setara dengan UK undergraduate 2:1",
            "Diterima di 3 universitas berbeda di UK",
            "Memenuhi syarat bahasa Inggris (IELTS 6.5)",
            "Tidak ada batasan usia maksimal",
        ],
        "url": "https://www.chevening.org",
        "image": "https://images.pexels.com/photos/31656148/pexels-photo-31656148.jpeg",
    },
    {
        "id": "australia-awards",
        "name": "Australia Awards Scholarship",
        "country": "Australia",
        "country_code": "AU",
        "degree": "S2",
        "deadline": "2027-04-30",
        "age_min": 18,
        "age_max": 42,
        "benefits": [
            "Full tuition fees",
            "Tiket pulang pergi",
            "Establishment allowance AUD 5,000",
            "Contribution to Living Expenses (CLE)",
            "Overseas Student Health Cover (OSHC)",
            "Pre-course English (PCE)",
        ],
        "requirements": [
            "Berusia minimal 18 tahun saat 1 Februari tahun keberangkatan",
            "Berusia maksimal 42 tahun untuk PNS/swasta",
            "WNI dan tidak menikah dengan WN Australia/NZ",
            "IELTS 6.5 (no band below 6.0) atau TOEFL iBT 84",
            "IPK minimum 2.9 (umum) atau 2.75 (focus area)",
        ],
        "url": "https://www.australiaawardsindonesia.org",
        "image": "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=800",
    },
    {
        "id": "daad-epos",
        "name": "DAAD EPOS Scholarship",
        "country": "Germany",
        "country_code": "DE",
        "degree": "S2",
        "deadline": "2026-09-30",
        "age_min": 21,
        "age_max": None,
        "benefits": [
            "Monthly stipend €934",
            "Health, accident, personal liability insurance",
            "Travel allowance",
            "Study & research allowance",
            "Rent subsidy & family allowance jika ada",
        ],
        "requirements": [
            "Pengalaman kerja minimal 2 tahun (untuk negara berkembang)",
            "S1 dengan IPK baik (umumnya >3.0)",
            "Gelar S1 tidak boleh lebih dari 6 tahun",
            "IELTS 6.0+ atau bukti bahasa Jerman (program spesifik)",
            "Tidak ada batasan usia maksimal eksplisit",
        ],
        "url": "https://www.daad.de",
        "image": "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800",
    },
    {
        "id": "lpdp",
        "name": "LPDP Reguler (Luar Negeri)",
        "country": "Multi-country",
        "country_code": "ID",
        "degree": "S2",
        "deadline": "2026-08-15",
        "age_min": 18,
        "age_max": 42,
        "benefits": [
            "Tuition fees full",
            "Living allowance bulanan sesuai kota tujuan",
            "Settlement allowance & buku",
            "Asuransi kesehatan",
            "Tiket pesawat PP",
            "Visa & tunjangan keluarga (S3)",
        ],
        "requirements": [
            "WNI",
            "Usia maksimal 35 tahun (S2 reguler), 42 tahun (PNS/TNI/Polri)",
            "S1 dari PT terakreditasi, IPK min 3.0",
            "LoA Unconditional dari universitas tujuan",
            "Skor bahasa: IELTS 6.5 / TOEFL iBT 80",
            "Esai kontribusi & komitmen kembali ke Indonesia",
        ],
        "url": "https://lpdp.kemenkeu.go.id",
        "image": "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    },
    {
        "id": "erasmus-mundus",
        "name": "Erasmus Mundus Joint Masters",
        "country": "Europe (Multi)",
        "country_code": "EU",
        "degree": "S2",
        "deadline": "2026-10-15",
        "age_min": 21,
        "age_max": None,
        "benefits": [
            "Tuition fees full + participation costs",
            "Monthly allowance €1,400",
            "Travel & installation costs",
            "Insurance contribution",
            "Belajar di 2-3 universitas Eropa",
        ],
        "requirements": [
            "Gelar S1 setara EU bachelor",
            "Tidak ada batasan usia formal",
            "English proficiency (IELTS 6.5+)",
            "Komitmen mobility ke beberapa negara EU",
            "2 letter of recommendation",
        ],
        "url": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
        "image": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800",
    },
    {
        "id": "fulbright",
        "name": "Fulbright Foreign Student Program",
        "country": "United States",
        "country_code": "US",
        "degree": "S2",
        "deadline": "2026-10-15",
        "age_min": 21,
        "age_max": None,
        "benefits": [
            "J-1 visa sponsorship",
            "Round-trip airfare",
            "Tuition & fees full",
            "Monthly living stipend",
            "Health & accident insurance",
            "Book & settling-in allowance",
        ],
        "requirements": [
            "WNI, tidak punya green card / kewarganegaraan US",
            "S1 dengan IPK minimum 3.0",
            "TOEFL iBT 80+ atau IELTS 6.5",
            "Tidak ada batasan usia",
            "Komitmen kembali ke Indonesia 2 tahun",
        ],
        "url": "https://www.aminef.or.id",
        "image": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800",
    },
    {
        "id": "mext",
        "name": "MEXT Japanese Government Scholarship",
        "country": "Japan",
        "country_code": "JP",
        "degree": "S2",
        "deadline": "2027-05-31",
        "age_min": 18,
        "age_max": 34,
        "benefits": [
            "Tuition fees full",
            "Monthly stipend ¥144,000–145,000",
            "Round-trip airfare",
            "Tidak ada ikatan dinas",
            "Pre-arrival Japanese training",
        ],
        "requirements": [
            "Lahir setelah 2 April 1991 (usia maks 34)",
            "S1 dengan IPK 3.2+ (atau setara 80/100)",
            "TOEFL/IELTS atau JLPT N2+",
            "Sehat jasmani dan rohani",
        ],
        "url": "https://www.id.emb-japan.go.jp",
        "image": "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800",
    },
    {
        "id": "swedish-institute",
        "name": "Swedish Institute Scholarships for Global Professionals",
        "country": "Sweden",
        "country_code": "SE",
        "degree": "S2",
        "deadline": "2026-11-14",
        "age_min": 21,
        "age_max": None,
        "benefits": [
            "Tuition fee full",
            "Living costs SEK 12,000/bulan",
            "Travel grant SEK 15,000",
            "Insurance",
            "SI Network for Future Global Leaders",
        ],
        "requirements": [
            "Pengalaman kerja min 3,000 jam",
            "Bukti pengalaman kepemimpinan",
            "Diterima di program master eligible",
            "Tidak ada batas usia",
            "Komitmen leadership di home country",
        ],
        "url": "https://si.se/en/apply/scholarships/",
        "image": "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800",
    },
]

# ============ TOP COMPANIES (jobs) ============
TOP_COMPANIES = [
    {"id": "google", "name": "Google", "industry": "Technology", "location": "Mountain View, USA", "remote": True, "roles": ["Software Engineer", "Product Manager", "UX Designer", "Data Scientist"], "salary_usd": "150,000 - 350,000", "logo": "https://logo.clearbit.com/google.com", "url": "https://careers.google.com"},
    {"id": "meta", "name": "Meta", "industry": "Social / AR/VR", "location": "Menlo Park, USA", "remote": True, "roles": ["Software Engineer", "Research Scientist", "Designer"], "salary_usd": "160,000 - 400,000", "logo": "https://logo.clearbit.com/meta.com", "url": "https://www.metacareers.com"},
    {"id": "microsoft", "name": "Microsoft", "industry": "Cloud / AI", "location": "Redmond, USA", "remote": True, "roles": ["SDE", "Cloud Architect", "Program Manager"], "salary_usd": "140,000 - 320,000", "logo": "https://logo.clearbit.com/microsoft.com", "url": "https://careers.microsoft.com"},
    {"id": "apple", "name": "Apple", "industry": "Hardware / Software", "location": "Cupertino, USA", "remote": False, "roles": ["Hardware Engineer", "iOS Developer", "Designer"], "salary_usd": "150,000 - 380,000", "logo": "https://logo.clearbit.com/apple.com", "url": "https://www.apple.com/careers"},
    {"id": "amazon", "name": "Amazon / AWS", "industry": "E-commerce / Cloud", "location": "Seattle, USA", "remote": True, "roles": ["SDE", "Solutions Architect", "Product Manager"], "salary_usd": "130,000 - 320,000", "logo": "https://logo.clearbit.com/amazon.com", "url": "https://www.amazon.jobs"},
    {"id": "netflix", "name": "Netflix", "industry": "Streaming", "location": "Los Gatos, USA", "remote": True, "roles": ["Senior Engineer", "Data Engineer", "Content Strategist"], "salary_usd": "200,000 - 500,000", "logo": "https://logo.clearbit.com/netflix.com", "url": "https://jobs.netflix.com"},
    {"id": "nvidia", "name": "NVIDIA", "industry": "GPU / AI", "location": "Santa Clara, USA", "remote": True, "roles": ["AI Researcher", "GPU Engineer", "Solutions Architect"], "salary_usd": "180,000 - 450,000", "logo": "https://logo.clearbit.com/nvidia.com", "url": "https://www.nvidia.com/en-us/about-nvidia/careers/"},
    {"id": "openai", "name": "OpenAI", "industry": "AI Research", "location": "San Francisco, USA", "remote": True, "roles": ["Research Engineer", "ML Engineer", "Policy"], "salary_usd": "250,000 - 700,000", "logo": "https://logo.clearbit.com/openai.com", "url": "https://openai.com/careers"},
    {"id": "anthropic", "name": "Anthropic", "industry": "AI Safety", "location": "San Francisco, USA", "remote": True, "roles": ["ML Researcher", "Software Engineer"], "salary_usd": "300,000 - 800,000", "logo": "https://logo.clearbit.com/anthropic.com", "url": "https://www.anthropic.com/careers"},
    {"id": "spotify", "name": "Spotify", "industry": "Music Streaming", "location": "Stockholm, Sweden", "remote": True, "roles": ["Engineer", "Data Scientist", "Designer"], "salary_usd": "100,000 - 220,000", "logo": "https://logo.clearbit.com/spotify.com", "url": "https://www.lifeatspotify.com"},
    {"id": "atlassian", "name": "Atlassian", "industry": "SaaS / Productivity", "location": "Sydney, Australia", "remote": True, "roles": ["Engineer", "PM", "Designer"], "salary_usd": "110,000 - 240,000", "logo": "https://logo.clearbit.com/atlassian.com", "url": "https://www.atlassian.com/company/careers"},
    {"id": "shopify", "name": "Shopify", "industry": "E-commerce", "location": "Ottawa, Canada", "remote": True, "roles": ["Developer", "Designer", "Support Engineer"], "salary_usd": "120,000 - 260,000", "logo": "https://logo.clearbit.com/shopify.com", "url": "https://www.shopify.com/careers"},
    {"id": "stripe", "name": "Stripe", "industry": "Fintech", "location": "San Francisco / Dublin", "remote": True, "roles": ["Engineer", "Designer", "Risk Analyst"], "salary_usd": "150,000 - 350,000", "logo": "https://logo.clearbit.com/stripe.com", "url": "https://stripe.com/jobs"},
    {"id": "tesla", "name": "Tesla", "industry": "EV / Energy", "location": "Austin, USA", "remote": False, "roles": ["Engineer", "Manufacturing", "Designer"], "salary_usd": "120,000 - 280,000", "logo": "https://logo.clearbit.com/tesla.com", "url": "https://www.tesla.com/careers"},
    {"id": "siemens", "name": "Siemens", "industry": "Industrial / Energy", "location": "Munich, Germany", "remote": False, "roles": ["Engineer", "Project Manager", "Consultant"], "salary_usd": "80,000 - 180,000", "logo": "https://logo.clearbit.com/siemens.com", "url": "https://jobs.siemens.com"},
    {"id": "sap", "name": "SAP", "industry": "Enterprise Software", "location": "Walldorf, Germany", "remote": True, "roles": ["Developer", "Consultant", "Product Manager"], "salary_usd": "90,000 - 200,000", "logo": "https://logo.clearbit.com/sap.com", "url": "https://jobs.sap.com"},
]

# ============ FREELANCER SITES ============
FREELANCE_SITES = [
    {"id": "toptal", "name": "Toptal", "category": "Premium Talent", "rating": 4.7, "description": "Top 3% freelancer global. Very selective, high paying ($60-200/hour).", "url": "https://www.toptal.com", "logo": "https://logo.clearbit.com/toptal.com", "scam_risk": "Very Low"},
    {"id": "upwork", "name": "Upwork", "category": "General Marketplace", "rating": 4.3, "description": "Marketplace freelance global terbesar, semua skill level.", "url": "https://www.upwork.com", "logo": "https://logo.clearbit.com/upwork.com", "scam_risk": "Low"},
    {"id": "fiverr", "name": "Fiverr", "category": "Gig-based", "rating": 4.2, "description": "Sistem gig — Anda buat layanan, klien membeli. Cocok untuk creative & micro service.", "url": "https://www.fiverr.com", "logo": "https://logo.clearbit.com/fiverr.com", "scam_risk": "Low"},
    {"id": "freelancer", "name": "Freelancer.com", "category": "General Marketplace", "rating": 3.9, "description": "Bidding system. Banyak project tapi kompetisi tinggi.", "url": "https://www.freelancer.com", "logo": "https://logo.clearbit.com/freelancer.com", "scam_risk": "Medium"},
    {"id": "contra", "name": "Contra", "category": "Commission-free", "rating": 4.5, "description": "Independent platform — 0% commission. Cocok untuk designer & strategist.", "url": "https://contra.com", "logo": "https://logo.clearbit.com/contra.com", "scam_risk": "Very Low"},
    {"id": "99designs", "name": "99designs", "category": "Design", "rating": 4.4, "description": "Khusus designer (logo, branding, web). Contest & 1-on-1 project.", "url": "https://99designs.com", "logo": "https://logo.clearbit.com/99designs.com", "scam_risk": "Very Low"},
    {"id": "arc", "name": "Arc.dev", "category": "Developer-only", "rating": 4.6, "description": "Khusus developer remote, focus full-time & long-term.", "url": "https://arc.dev", "logo": "https://logo.clearbit.com/arc.dev", "scam_risk": "Very Low"},
    {"id": "we-work-remotely", "name": "We Work Remotely", "category": "Remote Jobs Board", "rating": 4.5, "description": "Job board untuk pekerjaan remote full-time & contract.", "url": "https://weworkremotely.com", "logo": "https://logo.clearbit.com/weworkremotely.com", "scam_risk": "Very Low"},
    {"id": "remoteok", "name": "Remote OK", "category": "Remote Jobs Board", "rating": 4.4, "description": "Salah satu job board remote terbesar dan paling aktif.", "url": "https://remoteok.com", "logo": "https://logo.clearbit.com/remoteok.com", "scam_risk": "Very Low"},
    {"id": "dribbble", "name": "Dribbble", "category": "Design", "rating": 4.5, "description": "Portfolio + freelance untuk designer kelas dunia.", "url": "https://dribbble.com", "logo": "https://logo.clearbit.com/dribbble.com", "scam_risk": "Very Low"},
]

# ============ STOCKS (Indonesia & Global) — curated picks for educational purpose ============
STOCKS_ID = [
    {"ticker":"BBCA","name":"Bank Central Asia","sector":"Banking","price_idr":10100,"change_pct":0.5,"rec":"BUY",
     "rationale":"Bank swasta ROE tertinggi di Indonesia. NIM konsisten >5%, digital banking (myBCA) tumbuh 30% YoY. Bank paling efisien di ASEAN dengan BOPO ~40%.",
     "fundamental":{"pe_trailing":23.1,"pe_forward":20.4,"pb":4.1,"eps_idr":437,"market_cap_t":1234,"roe_pct":22.5,"der":0.8,"npm_pct":40.2,"beli_ideal_idr":"8.500–9.500","target_price_idr":12000,"risk":"Rendah"},
     "dividend":{"yield_pct":2.1,"cum_date":"2026-04-15","ex_date":"2026-04-16","payment_date":"2026-05-05","freq":"Annual","note":"Dividen interim biasa dibagikan Desember",
      "history":[{"year":2025,"ex_date":"2025-04-18","amount_idr":340,"yield_pct":2.3},{"year":2024,"ex_date":"2024-04-19","amount_idr":290,"yield_pct":2.1},{"year":2023,"ex_date":"2023-04-14","amount_idr":260,"yield_pct":2.0},{"year":2022,"ex_date":"2022-04-15","amount_idr":216,"yield_pct":2.0},{"year":2021,"ex_date":"2021-04-16","amount_idr":170,"yield_pct":1.9}]}},
    {"ticker":"BBRI","name":"Bank Rakyat Indonesia","sector":"Banking","price_idr":4480,"change_pct":-0.3,"rec":"BUY",
     "rationale":"Bank BUMN terbesar, penetrasi UMKM ~43% total kredit. Program KUR pemerintah jadi katalis. Dividend yield konsisten >5% dengan payout ratio ~65% laba bersih.",
     "fundamental":{"pe_trailing":11.2,"pe_forward":10.1,"pb":2.1,"eps_idr":400,"market_cap_t":671,"roe_pct":18.3,"der":7.2,"npm_pct":33.5,"beli_ideal_idr":"3.800–4.200","target_price_idr":5200,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":6.2,"cum_date":"2026-03-28","ex_date":"2026-03-29","payment_date":"2026-04-20","freq":"Annual","note":"Salah satu dividen terbesar di IDX",
      "history":[{"year":2025,"ex_date":"2025-04-01","amount_idr":278,"yield_pct":5.8},{"year":2024,"ex_date":"2024-04-02","amount_idr":255,"yield_pct":5.4},{"year":2023,"ex_date":"2023-03-30","amount_idr":235,"yield_pct":5.2},{"year":2022,"ex_date":"2022-03-28","amount_idr":174,"yield_pct":4.4},{"year":2021,"ex_date":"2021-03-30","amount_idr":85,"yield_pct":2.8}]}},
    {"ticker":"BBNI","name":"Bank BNI","sector":"Banking","price_idr":4890,"change_pct":0.8,"rec":"BUY",
     "rationale":"Transformasi digital terbaik BUMN perbankan. ROE dari 12% (2021) ke 17% (2025). P/BV 1.5x masih discount 40% vs BBCA — ada ruang re-rating signifikan.",
     "fundamental":{"pe_trailing":8.9,"pe_forward":8.1,"pb":1.5,"eps_idr":549,"market_cap_t":187,"roe_pct":17.2,"der":6.5,"npm_pct":30.1,"beli_ideal_idr":"4.200–4.600","target_price_idr":5800,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":5.1,"cum_date":"2026-04-05","ex_date":"2026-04-06","payment_date":"2026-04-28","freq":"Annual","note":"Payout ratio ~45% laba bersih",
      "history":[{"year":2025,"ex_date":"2025-04-08","amount_idr":248,"yield_pct":4.9},{"year":2024,"ex_date":"2024-04-05","amount_idr":221,"yield_pct":4.6},{"year":2023,"ex_date":"2023-04-06","amount_idr":197,"yield_pct":4.3},{"year":2022,"ex_date":"2022-04-07","amount_idr":134,"yield_pct":3.5},{"year":2021,"ex_date":"2021-04-06","amount_idr":47,"yield_pct":1.8}]}},
    {"ticker":"TLKM","name":"Telkom Indonesia","sector":"Telco","price_idr":2850,"change_pct":0.2,"rec":"HOLD",
     "rationale":"Defensive telco. Revenue data center (NeutraDC) tumbuh 22% YoY. Core telco stagnan tapi dividen semi-annual konsisten menjadikannya pilihan income investor.",
     "fundamental":{"pe_trailing":14.2,"pe_forward":13.5,"pb":2.9,"eps_idr":201,"market_cap_t":281,"roe_pct":22.8,"der":0.9,"npm_pct":23.4,"beli_ideal_idr":"2.500–2.700","target_price_idr":3200,"risk":"Rendah"},
     "dividend":{"yield_pct":4.8,"cum_date":"2026-05-10","ex_date":"2026-05-11","payment_date":"2026-06-01","freq":"Semi-Annual","note":"Interim + final dividend dua kali setahun",
      "history":[{"year":2025,"ex_date":"2025-06-02","amount_idr":136,"yield_pct":4.6},{"year":2024,"ex_date":"2024-06-03","amount_idr":128,"yield_pct":4.3},{"year":2023,"ex_date":"2023-06-01","amount_idr":125,"yield_pct":4.2},{"year":2022,"ex_date":"2022-05-31","amount_idr":119,"yield_pct":3.8},{"year":2021,"ex_date":"2021-06-02","amount_idr":106,"yield_pct":3.4}]}},
    {"ticker":"ASII","name":"Astra International","sector":"Conglomerate","price_idr":5025,"change_pct":1.1,"rec":"BUY",
     "rationale":"Konglomerat terdiversifikasi: otomotif (Toyota, Daihatsu) 47% revenue + perkebunan + infrastruktur. Beneficiary kenaikan penjualan mobil & EV partnership Toyota.",
     "fundamental":{"pe_trailing":12.3,"pe_forward":11.1,"pb":1.8,"eps_idr":408,"market_cap_t":204,"roe_pct":15.6,"der":1.2,"npm_pct":7.8,"beli_ideal_idr":"4.400–4.800","target_price_idr":6000,"risk":"Sedang"},
     "dividend":{"yield_pct":4.5,"cum_date":"2026-04-20","ex_date":"2026-04-21","payment_date":"2026-05-10","freq":"Annual","note":"Payout ratio historis ~50% laba bersih",
      "history":[{"year":2025,"ex_date":"2025-04-22","amount_idr":226,"yield_pct":4.3},{"year":2024,"ex_date":"2024-04-23","amount_idr":215,"yield_pct":4.1},{"year":2023,"ex_date":"2023-04-20","amount_idr":199,"yield_pct":3.9},{"year":2022,"ex_date":"2022-04-22","amount_idr":165,"yield_pct":3.4},{"year":2021,"ex_date":"2021-04-21","amount_idr":53,"yield_pct":1.3}]}},
    {"ticker":"ITMG","name":"Indo Tambangraya Megah","sector":"Coal Mining","price_idr":27800,"change_pct":1.3,"rec":"BUY",
     "rationale":"Top dividend play IDX 3 tahun berturut-turut. Cash & cash equivalent Rp 6T hampir setara market cap. Batubara thermal global masih dibutuhkan Asia untuk transisi energi.",
     "fundamental":{"pe_trailing":5.1,"pe_forward":5.8,"pb":1.8,"eps_idr":5451,"market_cap_t":31.7,"roe_pct":38.2,"der":0.1,"npm_pct":28.4,"beli_ideal_idr":"22.000–25.000","target_price_idr":34000,"risk":"Sedang (siklus komoditas)"},
     "dividend":{"yield_pct":12.5,"cum_date":"2026-03-20","ex_date":"2026-03-21","payment_date":"2026-04-10","freq":"Interim+Final","note":"⭐ Top dividen IDX — yield >10% konsisten 3 tahun",
      "history":[{"year":2025,"ex_date":"2025-03-21","amount_idr":3476,"yield_pct":13.2},{"year":2024,"ex_date":"2024-03-20","amount_idr":3281,"yield_pct":11.9},{"year":2023,"ex_date":"2023-03-22","amount_idr":4890,"yield_pct":16.8},{"year":2022,"ex_date":"2022-03-21","amount_idr":8240,"yield_pct":24.1},{"year":2021,"ex_date":"2021-03-22","amount_idr":1450,"yield_pct":8.2}]}},
    {"ticker":"PTBA","name":"Bukit Asam","sector":"Coal Mining","price_idr":3180,"change_pct":0.9,"rec":"BUY",
     "rationale":"BUMN batubara dengan cadangan terbesar di Sumatera. Diversifikasi ke PLTU mulut tambang + coal-to-chemicals. Dividend yield ~10% konsisten dan predictable.",
     "fundamental":{"pe_trailing":6.2,"pe_forward":6.8,"pb":1.9,"eps_idr":513,"market_cap_t":36.6,"roe_pct":31.2,"der":0.3,"npm_pct":26.1,"beli_ideal_idr":"2.600–2.900","target_price_idr":4000,"risk":"Sedang (siklus komoditas)"},
     "dividend":{"yield_pct":9.8,"cum_date":"2026-04-02","ex_date":"2026-04-03","payment_date":"2026-04-25","freq":"Annual","note":"⭐ Salah satu top dividen BUMN IDX",
      "history":[{"year":2025,"ex_date":"2025-04-04","amount_idr":311,"yield_pct":9.2},{"year":2024,"ex_date":"2024-04-05","amount_idr":295,"yield_pct":8.8},{"year":2023,"ex_date":"2023-04-03","amount_idr":509,"yield_pct":13.1},{"year":2022,"ex_date":"2022-04-04","amount_idr":636,"yield_pct":14.9},{"year":2021,"ex_date":"2021-04-02","amount_idr":193,"yield_pct":6.1}]}},
    {"ticker":"ADRO","name":"Adaro Energy Indonesia","sector":"Coal Mining","price_idr":2180,"change_pct":1.5,"rec":"BUY",
     "rationale":"Transformasi dari pure-play coal ke green energy (AADI). Proyek aluminium smelter Kaltara + green hydrogen jadi pendorong valuasi. Balance sheet bersih, net cash positif.",
     "fundamental":{"pe_trailing":7.4,"pe_forward":8.1,"pb":1.3,"eps_idr":295,"market_cap_t":69.6,"roe_pct":18.9,"der":0.2,"npm_pct":24.8,"beli_ideal_idr":"1.800–2.000","target_price_idr":2800,"risk":"Sedang"},
     "dividend":{"yield_pct":7.3,"cum_date":"2026-04-12","ex_date":"2026-04-13","payment_date":"2026-05-02","freq":"Annual","note":"Ekspansi ke green hydrogen & aluminium smelter",
      "history":[{"year":2025,"ex_date":"2025-04-14","amount_idr":159,"yield_pct":6.9},{"year":2024,"ex_date":"2024-04-15","amount_idr":144,"yield_pct":6.3},{"year":2023,"ex_date":"2023-04-10","amount_idr":258,"yield_pct":9.8},{"year":2022,"ex_date":"2022-04-11","amount_idr":263,"yield_pct":8.4},{"year":2021,"ex_date":"2021-04-12","amount_idr":42,"yield_pct":1.8}]}},
    {"ticker":"ANTM","name":"Aneka Tambang","sector":"Mining (Gold/Nickel)","price_idr":1635,"change_pct":2.0,"rec":"BUY",
     "rationale":"Double beneficiary: harga emas di ATH + nikel EV. Satu-satunya emiten IDX eksposur langsung ke keduanya. Pabrik pemurnian nikel Pomalaa jadi keunggulan kompetitif.",
     "fundamental":{"pe_trailing":18.4,"pe_forward":15.2,"pb":1.6,"eps_idr":89,"market_cap_t":39.3,"roe_pct":9.2,"der":0.6,"npm_pct":8.4,"beli_ideal_idr":"1.350–1.500","target_price_idr":2100,"risk":"Sedang–Tinggi"},
     "dividend":{"yield_pct":3.8,"cum_date":"2026-05-15","ex_date":"2026-05-16","payment_date":"2026-06-05","freq":"Annual","note":"Dividen terkait kinerja harga komoditas",
      "history":[{"year":2025,"ex_date":"2025-05-16","amount_idr":62,"yield_pct":3.5},{"year":2024,"ex_date":"2024-05-17","amount_idr":53,"yield_pct":3.2},{"year":2023,"ex_date":"2023-05-15","amount_idr":47,"yield_pct":3.1},{"year":2022,"ex_date":"2022-05-16","amount_idr":68,"yield_pct":3.8},{"year":2021,"ex_date":"2021-05-17","amount_idr":22,"yield_pct":2.2}]}},
    {"ticker":"PGEO","name":"Pertamina Geothermal Energy","sector":"Renewable Energy","price_idr":1425,"change_pct":0.6,"rec":"BUY",
     "rationale":"Pure-play geothermal terbesar di dunia by capacity. Revenue 100% USD via kontrak PLN jangka panjang. ESG premium. Potensi ekspansi ke Kenya & Amerika Selatan.",
     "fundamental":{"pe_trailing":21.3,"pe_forward":18.8,"pb":3.1,"eps_idr":67,"market_cap_t":32.5,"roe_pct":15.8,"der":1.2,"npm_pct":35.6,"beli_ideal_idr":"1.200–1.350","target_price_idr":1800,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":5.2,"cum_date":"2026-06-10","ex_date":"2026-06-11","payment_date":"2026-07-01","freq":"Annual","note":"Bisnis stabil, kontrak offtake PLN jangka panjang",
      "history":[{"year":2025,"ex_date":"2025-06-12","amount_idr":74,"yield_pct":5.0},{"year":2024,"ex_date":"2024-06-10","amount_idr":68,"yield_pct":4.7},{"year":2023,"ex_date":"2023-06-09","amount_idr":61,"yield_pct":4.4},{"year":2022,"ex_date":"2022-06-10","amount_idr":55,"yield_pct":4.1},{"year":2021,"ex_date":"2021-06-11","amount_idr":48,"yield_pct":3.8}]}},
    {"ticker":"PGAS","name":"Perusahaan Gas Negara","sector":"Energy Infrastructure","price_idr":1580,"change_pct":-0.4,"rec":"HOLD",
     "rationale":"Monopoli distribusi gas. Pendapatan ultra-stabil karena tarif diatur pemerintah. Cocok investor konservatif yang inginkan yield ~6% risiko sangat rendah.",
     "fundamental":{"pe_trailing":8.9,"pe_forward":8.3,"pb":1.1,"eps_idr":178,"market_cap_t":38.4,"roe_pct":12.6,"der":0.9,"npm_pct":14.3,"beli_ideal_idr":"1.400–1.550","target_price_idr":1900,"risk":"Rendah"},
     "dividend":{"yield_pct":6.1,"cum_date":"2026-05-08","ex_date":"2026-05-09","payment_date":"2026-05-28","freq":"Annual","note":"Yield stabil karena bisnis utilitas yang predictable",
      "history":[{"year":2025,"ex_date":"2025-05-10","amount_idr":96,"yield_pct":5.9},{"year":2024,"ex_date":"2024-05-09","amount_idr":88,"yield_pct":5.6},{"year":2023,"ex_date":"2023-05-08","amount_idr":81,"yield_pct":5.3},{"year":2022,"ex_date":"2022-05-09","amount_idr":73,"yield_pct":4.9},{"year":2021,"ex_date":"2021-05-10","amount_idr":62,"yield_pct":4.5}]}},
    {"ticker":"BNGA","name":"Bank CIMB Niaga","sector":"Banking","price_idr":1245,"change_pct":0.3,"rec":"BUY",
     "rationale":"P/BV 0.9x (below book) — murah secara historis. ROE naik 9%→14% dalam 3 tahun. OCTO Mobile salah satu super app perbankan terbaik Indonesia.",
     "fundamental":{"pe_trailing":5.8,"pe_forward":5.2,"pb":0.9,"eps_idr":215,"market_cap_t":30.5,"roe_pct":14.3,"der":7.1,"npm_pct":23.1,"beli_ideal_idr":"1.050–1.200","target_price_idr":1600,"risk":"Sedang"},
     "dividend":{"yield_pct":4.7,"cum_date":"2026-04-18","ex_date":"2026-04-19","payment_date":"2026-05-08","freq":"Annual","note":"Upside signifikan jika re-rating valuasi terjadi",
      "history":[{"year":2025,"ex_date":"2025-04-21","amount_idr":58,"yield_pct":4.5},{"year":2024,"ex_date":"2024-04-19","amount_idr":52,"yield_pct":4.2},{"year":2023,"ex_date":"2023-04-17","amount_idr":43,"yield_pct":3.9},{"year":2022,"ex_date":"2022-04-18","amount_idr":35,"yield_pct":3.4},{"year":2021,"ex_date":"2021-04-19","amount_idr":21,"yield_pct":2.6}]}},
    {"ticker":"GOTO","name":"GoTo Gojek Tokopedia","sector":"Tech","price_idr":86,"change_pct":-1.2,"rec":"SPECULATIVE BUY",
     "rationale":"Path to profitability mulai jelas di GoPay. GMV stabil Rp 700T. Risiko: burn rate masih tinggi, persaingan Shopee/TikTok Shop intensif. Hanya untuk risk-tolerant investor.",
     "fundamental":{"pe_trailing":None,"pe_forward":None,"pb":0.6,"eps_idr":-8,"market_cap_t":10.6,"roe_pct":-5.2,"der":0.4,"npm_pct":-3.1,"beli_ideal_idr":"70–85","target_price_idr":130,"risk":"Tinggi"},
     "dividend":None},
    {"ticker":"UNVR","name":"Unilever Indonesia","sector":"Consumer","price_idr":1810,"change_pct":-0.5,"rec":"HOLD",
     "rationale":"Brand portfolio legendaris (Rinso, Sunsilk, Wall's) masih kuat. Namun volume penjualan turun 3 tahun berturut karena persaingan FMCG lokal & penurunan daya beli.",
     "fundamental":{"pe_trailing":16.8,"pe_forward":15.4,"pb":14.2,"eps_idr":108,"market_cap_t":69.2,"roe_pct":82.3,"der":1.8,"npm_pct":18.2,"beli_ideal_idr":"1.600–1.750","target_price_idr":2200,"risk":"Sedang"},
     "dividend":{"yield_pct":5.8,"cum_date":"2026-07-20","ex_date":"2026-07-21","payment_date":"2026-08-10","freq":"Quarterly","note":"Dividen 4× setahun, konsisten bertahun-tahun",
      "history":[{"year":2025,"ex_date":"2025-07-22","amount_idr":105,"yield_pct":5.6},{"year":2024,"ex_date":"2024-07-23","amount_idr":99,"yield_pct":5.3},{"year":2023,"ex_date":"2023-07-21","amount_idr":91,"yield_pct":4.8},{"year":2022,"ex_date":"2022-07-22","amount_idr":81,"yield_pct":4.1},{"year":2021,"ex_date":"2021-07-21","amount_idr":66,"yield_pct":3.1}]}},
    {"ticker":"ICBP","name":"Indofood CBP","sector":"Consumer Staples","price_idr":11400,"change_pct":0.7,"rec":"BUY",
     "rationale":"Indomie hadir di 100+ negara — consumer staple paling terdiversifikasi di Indonesia. Akuisisi Pinehill tambah 30% revenue. Margin stabil di semua siklus ekonomi.",
     "fundamental":{"pe_trailing":15.2,"pe_forward":13.8,"pb":2.8,"eps_idr":750,"market_cap_t":66.5,"roe_pct":19.4,"der":0.7,"npm_pct":11.3,"beli_ideal_idr":"9.500–10.500","target_price_idr":13500,"risk":"Rendah"},
     "dividend":{"yield_pct":2.9,"cum_date":"2026-05-25","ex_date":"2026-05-26","payment_date":"2026-06-15","freq":"Annual","note":"Indomie di 100+ negara, revenue terdiversifikasi",
      "history":[{"year":2025,"ex_date":"2025-05-27","amount_idr":330,"yield_pct":2.8},{"year":2024,"ex_date":"2024-05-28","amount_idr":298,"yield_pct":2.5},{"year":2023,"ex_date":"2023-05-26","amount_idr":267,"yield_pct":2.3},{"year":2022,"ex_date":"2022-05-27","amount_idr":251,"yield_pct":2.2},{"year":2021,"ex_date":"2021-05-25","amount_idr":220,"yield_pct":2.0}]}},
]

STOCKS_GLOBAL = [
    {"ticker":"NVDA","name":"NVIDIA","sector":"Semiconductor / AI","price_usd":138.0,"change_pct":1.5,"rec":"BUY",
     "rationale":"Monopoli de facto AI compute: 80%+ market share GPU data center. Revenue data center tumbuh 400% YoY. CUDA moat sangat dalam — butuh 10+ tahun untuk digantikan. Blackwell architecture terbaru memperlebar keunggulan.",
     "fundamental":{"pe_trailing":52.1,"pe_forward":28.4,"pb":42.3,"eps_usd":2.65,"market_cap_b":3380,"roe_pct":123,"der":0.4,"npm_pct":55.0,"beli_ideal_usd":"110–130","target_price_usd":180,"risk":"Sedang–Tinggi (valuasi premium)"},
     "dividend":{"yield_pct":0.03,"freq":"Quarterly","note":"Dividend kecil, fokus buyback ($25B authorized)",
      "history":[{"year":2025,"ex_date":"2025-03-05","amount_usd":0.01,"yield_pct":0.03},{"year":2024,"ex_date":"2024-06-05","amount_usd":0.01,"yield_pct":0.03},{"year":2023,"ex_date":"2023-06-07","amount_usd":0.04,"yield_pct":0.04},{"year":2022,"ex_date":"2022-06-08","amount_usd":0.04,"yield_pct":0.04},{"year":2021,"ex_date":"2021-06-09","amount_usd":0.04,"yield_pct":0.07}]}},
    {"ticker":"MSFT","name":"Microsoft","sector":"Cloud / AI","price_usd":425.0,"change_pct":0.4,"rec":"BUY",
     "rationale":"Azure tumbuh 30% YoY, Copilot monetization baru mulai. Investasi $10B di OpenAI memberikan keunggulan AI yang unik. Quality compounder dengan FCF margin 35%+ dan neraca sangat kuat.",
     "fundamental":{"pe_trailing":37.8,"pe_forward":31.2,"pb":13.2,"eps_usd":11.25,"market_cap_b":3160,"roe_pct":36.5,"der":0.3,"npm_pct":35.9,"beli_ideal_usd":"380–410","target_price_usd":500,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":0.7,"freq":"Quarterly","note":"Dividend naik konsisten 10%/tahun selama 20 tahun",
      "history":[{"year":2025,"ex_date":"2025-02-19","amount_usd":0.75,"yield_pct":0.7},{"year":2024,"ex_date":"2024-02-14","amount_usd":0.68,"yield_pct":0.7},{"year":2023,"ex_date":"2023-02-15","amount_usd":0.62,"yield_pct":0.9},{"year":2022,"ex_date":"2022-02-16","amount_usd":0.62,"yield_pct":0.9},{"year":2021,"ex_date":"2021-02-17","amount_usd":0.56,"yield_pct":0.9}]}},
    {"ticker":"GOOGL","name":"Alphabet","sector":"Search / Cloud","price_usd":192.0,"change_pct":0.6,"rec":"BUY",
     "rationale":"Search masih dominan 90%+ market share. Google Cloud tumbuh 28% YoY. Gemini 2.0 memperkuat posisi AI. Valuasi paling murah di antara Magnificent 7 dengan P/E forward ~22x.",
     "fundamental":{"pe_trailing":24.1,"pe_forward":21.8,"pb":7.8,"eps_usd":7.97,"market_cap_b":2340,"roe_pct":34.2,"der":0.1,"npm_pct":29.5,"beli_ideal_usd":"165–185","target_price_usd":240,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":0.5,"freq":"Quarterly","note":"Baru mulai dividend 2024, fokus $70B buyback",
      "history":[{"year":2025,"ex_date":"2025-03-10","amount_usd":0.20,"yield_pct":0.4},{"year":2024,"ex_date":"2024-06-10","amount_usd":0.20,"yield_pct":0.4},{"year":2023,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2022,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2021,"ex_date":None,"amount_usd":0,"yield_pct":0}]}},
    {"ticker":"AAPL","name":"Apple","sector":"Hardware / Services","price_usd":232.0,"change_pct":-0.3,"rec":"HOLD",
     "rationale":"Services revenue ($100B/tahun) tumbuh 14% YoY dan margin 74%. iPhone cycle stabil. Apple Intelligence mulai dimonetisasi via Apple One+. Valuasi premium P/E 34x untuk hardware company perlu dicermati.",
     "fundamental":{"pe_trailing":34.2,"pe_forward":31.5,"pb":52.8,"eps_usd":6.79,"market_cap_b":3510,"roe_pct":147,"der":1.6,"npm_pct":26.4,"beli_ideal_usd":"195–220","target_price_usd":260,"risk":"Sedang"},
     "dividend":{"yield_pct":0.5,"freq":"Quarterly","note":"Dividend kecil relatif harga, fokus buyback $90B/tahun",
      "history":[{"year":2025,"ex_date":"2025-02-07","amount_usd":0.25,"yield_pct":0.5},{"year":2024,"ex_date":"2024-02-09","amount_usd":0.24,"yield_pct":0.5},{"year":2023,"ex_date":"2023-02-10","amount_usd":0.23,"yield_pct":0.6},{"year":2022,"ex_date":"2022-02-04","amount_usd":0.22,"yield_pct":0.7},{"year":2021,"ex_date":"2021-01-29","amount_usd":0.205,"yield_pct":0.6}]}},
    {"ticker":"TSLA","name":"Tesla","sector":"EV / Energy","price_usd":380.0,"change_pct":2.5,"rec":"HOLD",
     "rationale":"FSD v13 progres significant — full autonomy closer. Energy storage (Megapack) tumbuh 113% YoY. Tapi Cybertruck demand problem + Elon distraction + valuasi P/E 120x sangat stretched.",
     "fundamental":{"pe_trailing":120.5,"pe_forward":89.4,"pb":18.2,"eps_usd":3.16,"market_cap_b":1220,"roe_pct":12.3,"der":0.1,"npm_pct":7.3,"beli_ideal_usd":"250–320","target_price_usd":280,"risk":"Tinggi"},
     "dividend":{"yield_pct":0,"freq":"None","note":"Tidak membagikan dividen, semua reinvested R&D",
      "history":[{"year":2025,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2024,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2023,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2022,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2021,"ex_date":None,"amount_usd":0,"yield_pct":0}]}},
    {"ticker":"BRK-B","name":"Berkshire Hathaway","sector":"Conglomerate","price_usd":470.0,"change_pct":0.1,"rec":"BUY",
     "rationale":"Cash pile $167B menunggu opportunity. Portfolio saham: Apple, BoA, Chevron, Coke. Insurance float machine. Post-Buffett era uncertainty tapi manajemen succession sudah jelas (Greg Abel).",
     "fundamental":{"pe_trailing":23.4,"pe_forward":21.1,"pb":1.7,"eps_usd":20.08,"market_cap_b":1030,"roe_pct":9.8,"der":0.3,"npm_pct":14.2,"beli_ideal_usd":"420–455","target_price_usd":540,"risk":"Rendah"},
     "dividend":{"yield_pct":0,"freq":"None","note":"Buffett tidak percaya dividend — semua dicompound via reinvestment",
      "history":[{"year":2025,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2024,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2023,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2022,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2021,"ex_date":None,"amount_usd":0,"yield_pct":0}]}},
    {"ticker":"TSM","name":"Taiwan Semiconductor","sector":"Foundry","price_usd":195.0,"change_pct":1.0,"rec":"BUY",
     "rationale":"Monopoli foundry leading-edge (2nm/3nm) — semua chip AI NVDA, Apple, AMD dibuat di sini. Geopolitical risk (Taiwan Strait) diimbangi strategic value yang membuat US/Japan aktif protect via fab di Arizona.",
     "fundamental":{"pe_trailing":28.9,"pe_forward":23.4,"pb":8.4,"eps_usd":6.75,"market_cap_b":1010,"roe_pct":32.4,"der":0.3,"npm_pct":39.2,"beli_ideal_usd":"165–185","target_price_usd":240,"risk":"Sedang (geopolitical)"},
     "dividend":{"yield_pct":1.5,"freq":"Quarterly","note":"Konsisten naik setiap tahun sejak 2004",
      "history":[{"year":2025,"ex_date":"2025-03-18","amount_usd":0.72,"yield_pct":1.5},{"year":2024,"ex_date":"2024-03-19","amount_usd":0.62,"yield_pct":1.4},{"year":2023,"ex_date":"2023-03-21","amount_usd":0.55,"yield_pct":1.5},{"year":2022,"ex_date":"2022-03-22","amount_usd":0.48,"yield_pct":1.4},{"year":2021,"ex_date":"2021-03-23","amount_usd":0.44,"yield_pct":1.4}]}},
    {"ticker":"AMZN","name":"Amazon","sector":"E-commerce / AWS","price_usd":220.0,"change_pct":0.5,"rec":"BUY",
     "rationale":"AWS ($100B revenue/tahun) tumbuh 17% YoY dengan margin operasi 38%. Advertising tumbuh 19% jadi $50B/tahun. Prime membership base defensif. AI capital expenditure $75B akan menghasilkan ROI dalam 3-5 tahun.",
     "fundamental":{"pe_trailing":43.2,"pe_forward":34.8,"pb":9.4,"eps_usd":5.09,"market_cap_b":2330,"roe_pct":24.6,"der":0.5,"npm_pct":9.3,"beli_ideal_usd":"185–210","target_price_usd":270,"risk":"Rendah–Sedang"},
     "dividend":{"yield_pct":0,"freq":"None","note":"Tidak membagikan dividen — reinvest semua ke AWS & logistics",
      "history":[{"year":2025,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2024,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2023,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2022,"ex_date":None,"amount_usd":0,"yield_pct":0},{"year":2021,"ex_date":None,"amount_usd":0,"yield_pct":0}]}},
]


ALT_INVESTMENTS = [
    {"horizon": "Short Term (< 1 thn)", "options": [
        {"name": "Reksadana Pasar Uang", "yield": "5–6% p.a.", "risk": "Sangat Rendah", "note": "Likuid harian, cocok dana darurat & parking."},
        {"name": "Deposito BPR (LPS-protected)", "yield": "5.5–7% p.a.", "risk": "Rendah", "note": "Cek limit LPS (Rp 2 M / bank)."},
        {"name": "SBN Ritel (SBR/ST)", "yield": "6–7%", "risk": "Rendah", "note": "Floating rate, dijamin negara."},
    ]},
    {"horizon": "Mid Term (1–5 thn)", "options": [
        {"name": "Reksadana Pendapatan Tetap", "yield": "6–8% p.a.", "risk": "Sedang", "note": "Mix obligasi pemerintah & korporasi."},
        {"name": "ORI / Sukuk Ritel", "yield": "6.25–6.75%", "risk": "Rendah", "note": "Fixed coupon, dijual periodik."},
        {"name": "Emas Fisik / Digital", "yield": "Variable", "risk": "Sedang", "note": "Hedge inflasi & USD/IDR volatility."},
    ]},
    {"horizon": "Long Term (> 5 thn)", "options": [
        {"name": "Saham Blue Chip + DCA", "yield": "10–15% p.a. historis", "risk": "Tinggi", "note": "Beli rutin (Dollar Cost Avg) BBCA, BBRI, ASII."},
        {"name": "Reksadana Indeks (IDX30/LQ45)", "yield": "8–12% p.a.", "risk": "Tinggi", "note": "Murah, diversifikasi otomatis."},
        {"name": "ETF Global (VOO/VWRA)", "yield": "8–10% USD p.a.", "risk": "Tinggi", "note": "Akses pasar S&P500 / dunia."},
        {"name": "Properti (Lokasi Strategis)", "yield": "5–8% sewa + capital gain", "risk": "Sedang–Tinggi", "note": "Illiquid, butuh modal besar."},
    ]},
]

# ============ JOB TRENDS ============
JOB_TRENDS = {
    "current_year": [
        {"role": "AI/ML Engineer", "growth": "+38%", "median_salary_usd": "180,000", "demand": "Very High"},
        {"role": "Cybersecurity Specialist", "growth": "+32%", "median_salary_usd": "130,000", "demand": "Very High"},
        {"role": "Data Engineer", "growth": "+28%", "median_salary_usd": "140,000", "demand": "High"},
        {"role": "Cloud Architect", "growth": "+25%", "median_salary_usd": "165,000", "demand": "High"},
        {"role": "Renewable Energy Engineer", "growth": "+22%", "median_salary_usd": "110,000", "demand": "High"},
        {"role": "UX Researcher", "growth": "+18%", "median_salary_usd": "120,000", "demand": "Medium"},
        {"role": "Healthcare Data Analyst", "growth": "+20%", "median_salary_usd": "95,000", "demand": "High"},
    ],
    "five_year": [
        {"role": "AI Prompt Engineer / AI Trainer", "outlook": "Very Strong", "note": "Specialist yang menjembatani LLM dan industri vertical."},
        {"role": "Robotics & Automation", "outlook": "Strong", "note": "Robot humanoid scale-up, automasi pabrik & logistik."},
        {"role": "Climate Tech & Carbon Engineer", "outlook": "Strong", "note": "Net-zero pledges menciptakan demand massive."},
        {"role": "Quantum Computing Researcher", "outlook": "Emerging", "note": "Niche tapi gaji premium ekstrem."},
        {"role": "Biotech / Genetic Engineer", "outlook": "Strong", "note": "Personalized medicine & longevity."},
        {"role": "Synthetic Media / Content Creator AI", "outlook": "Strong", "note": "Industri kreatif berbasis AI tools."},
    ],
}

# ============ CITIES (Best to live) ============
BEST_CITIES = [
    {"city": "Vienna", "country": "Austria", "score": 99.1, "highlights": ["Kualitas hidup #1 (Mercer)", "Transportasi publik kelas dunia", "Universitas kuat", "Kuliner: Wiener Schnitzel, Sachertorte"], "avg_salary_usd": 60000, "flight_from_jkt": "USD 800–1,500", "image": "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800"},
    {"city": "Zurich", "country": "Switzerland", "score": 98.5, "highlights": ["Bersih & aman", "Lapangan kerja finance & tech", "Kuliner: Fondue, Rösti"], "avg_salary_usd": 95000, "flight_from_jkt": "USD 900–1,800", "image": "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800"},
    {"city": "Copenhagen", "country": "Denmark", "score": 97.8, "highlights": ["Sepeda lifestyle", "Hygge culture", "Pendidikan gratis untuk EU", "Kuliner: Smørrebrød"], "avg_salary_usd": 70000, "flight_from_jkt": "USD 850–1,600", "image": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800"},
    {"city": "Tokyo", "country": "Japan", "score": 96.5, "highlights": ["Transportasi efisien", "Aman", "Kuliner #1 dunia (Sushi, Ramen, Wagyu)"], "avg_salary_usd": 55000, "flight_from_jkt": "USD 500–900", "image": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800"},
    {"city": "Singapore", "country": "Singapore", "score": 95.9, "highlights": ["English friendly", "Asia hub", "Kuliner hawker centre", "Pajak rendah"], "avg_salary_usd": 70000, "flight_from_jkt": "USD 150–400", "image": "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800"},
    {"city": "Melbourne", "country": "Australia", "score": 94.7, "highlights": ["Coffee culture", "Universitas top dunia", "Multicultural"], "avg_salary_usd": 65000, "flight_from_jkt": "USD 600–1,200", "image": "https://images.unsplash.com/photo-1545044846-351ba102b6d5?w=800"},
    {"city": "Amsterdam", "country": "Netherlands", "score": 93.2, "highlights": ["Bilingual EN-NL", "Bike friendly", "Hub startup Eropa"], "avg_salary_usd": 65000, "flight_from_jkt": "USD 800–1,500", "image": "https://images.unsplash.com/photo-1534351590666-13e3e96c5017?w=800"},
    {"city": "Lisbon", "country": "Portugal", "score": 91.8, "highlights": ["Cuaca hangat", "Cost of living rendah", "Digital nomad visa", "Kuliner: Pastel de Nata, Bacalhau"], "avg_salary_usd": 35000, "flight_from_jkt": "USD 900–1,700", "image": "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800"},
]

# ============ TECH & GADGETS ============
TECH_GADGETS = [
    {"name": "Apple Vision Pro 2", "category": "AR/VR", "year": 2025, "price_usd": 2999, "highlight": "Spatial computing premium dengan eye-tracking, foveated rendering, integrasi macOS."},
    {"name": "Nvidia DGX Spark", "category": "AI Workstation", "year": 2025, "price_usd": 3999, "highlight": "AI supercomputer mini untuk dev — 1 PetaFLOP di desktop kecil."},
    {"name": "Meta Ray-Ban Smart Glasses Gen 3", "category": "Wearable", "year": 2025, "price_usd": 379, "highlight": "Kamera 12MP, live AI translate, audio open-ear, look natural."},
    {"name": "Samsung Galaxy S26 Ultra", "category": "Smartphone", "year": 2026, "price_usd": 1399, "highlight": "AI-first, kamera 200MP, satellite messaging, Galaxy AI on-device."},
    {"name": "Tesla Optimus Gen 3", "category": "Robotics", "year": 2026, "price_usd": 25000, "highlight": "Humanoid robot untuk consumer-grade tasks, mass production phase."},
    {"name": "Sony XR Cinema Glasses", "category": "Display", "year": 2025, "price_usd": 1199, "highlight": "Micro-OLED 4K per mata, kompak, IMAX-like personal screen."},
    {"name": "DJI Avata 3", "category": "Drone", "year": 2025, "price_usd": 999, "highlight": "FPV cinematic, obstacle avoidance, 8K log video."},
    {"name": "Framework Laptop 16 (Ryzen AI 9)", "category": "Laptop", "year": 2025, "price_usd": 1899, "highlight": "Modular fully repairable, NPU 50 TOPS, sustainability."},
    {"name": "Apple iPhone 17 Pro", "category": "Smartphone", "year": 2025, "price_usd": 1199, "highlight": "Titanium body, A19 chip, telephoto 5x periscope, on-device Apple Intelligence."},
    {"name": "Boston Dynamics Spot Mini", "category": "Robotics", "year": 2025, "price_usd": 74500, "highlight": "Quadruped robot untuk inspeksi industri & riset."},
]

# ============ TRAVELLING INDONESIA ============
TRAVEL_ID = [
    {"name": "Labuan Bajo & Komodo", "type": "Hidden Gem / Nature", "region": "NTT", "highlight": "Pink beach, Padar Island, Komodo dragon. Best snorkeling Indonesia.", "image": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800"},
    {"name": "Raja Ampat", "type": "Nature / Diving", "region": "Papua Barat", "highlight": "Biodiversitas laut #1 dunia. Wayag, Misool, Piaynemo viewpoint.", "image": "https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=800"},
    {"name": "Belitung", "type": "Hidden Gem / Beach", "region": "Bangka Belitung", "highlight": "Pantai granit unik, Lengkuas Island, Mie Belitung & gangan ikan.", "image": "https://images.unsplash.com/photo-1573919077090-ac3140d1d4cb?w=800"},
    {"name": "Bromo–Ijen–Tumpak Sewu", "type": "Nature / Adventure", "region": "Jawa Timur", "highlight": "Trio epik: sunrise Bromo, blue fire Ijen, air terjun Tumpak Sewu.", "image": "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800"},
    {"name": "Sumba", "type": "Hidden Gem", "region": "NTT", "highlight": "Pasola, bukit savana, Weekuri lagoon, kuliner kabuto & ayam pedas.", "image": "https://images.unsplash.com/photo-1571406384350-3cf7d09c5b25?w=800"},
    {"name": "Yogyakarta Kuliner", "type": "Culinary", "region": "DI Yogyakarta", "highlight": "Gudeg Yu Djum, Sate Klathak Pak Pong, Mangut Lele Mbah Marto, Bakmi Mbah Mo.", "image": "https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=800"},
    {"name": "Padang–Bukittinggi", "type": "Culinary / Nature", "region": "Sumatera Barat", "highlight": "Rendang asli, Sate Mak Syukur, Ngarai Sianok, Danau Maninjau.", "image": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800"},
    {"name": "Derawan & Maratua", "type": "Hidden Gem / Diving", "region": "Kalimantan Timur", "highlight": "Jellyfish lake, manta point, penyu hijau. Sepi & otentik.", "image": "https://images.unsplash.com/photo-1582637974316-d0db8de1c2e7?w=800"},
]

# ============ JAKARTA TODAY (curated agenda — will be augmented by AI) ============
JAKARTA_AGENDA = [
    {"title": "Jakarta International Marathon 2026", "date": "2026-03-15", "location": "Monas – Sudirman", "category": "Sports", "source": "@jakartamarathon"},
    {"title": "Java Jazz Festival", "date": "2026-05-29 to 2026-05-31", "location": "JIExpo Kemayoran", "category": "Music", "source": "@javajazzfest"},
    {"title": "Jakarta Fair (PRJ)", "date": "2026-06-12 to 2026-07-14", "location": "JIExpo Kemayoran", "category": "Festival", "source": "@jakartafair_official"},
    {"title": "Coldplay Music of the Spheres (Encore)", "date": "2026-04-22", "location": "GBK Senayan", "category": "Concert", "source": "@coldplay"},
    {"title": "Pameran Lukisan Affandi Retrospective", "date": "Ongoing – Maret 2026", "location": "Museum Nasional", "category": "Art", "source": "@museumnasionalindonesia"},
    {"title": "Indonesia International Auto Show (IIMS)", "date": "2026-02-20 to 2026-03-02", "location": "JIExpo Kemayoran", "category": "Exhibition", "source": "@iims_id"},
    {"title": "Hari ini di Jakarta: Cek MRT/LRT update", "date": "today", "location": "Seluruh Jakarta", "category": "Info", "source": "@mrtjakarta @lrtjakarta"},
]

# ============ OUR WORLD INSIGHTS (Curated from Our World in Data themes) ============
OWID_INSIGHTS = [
    {"topic": "Global Life Expectancy", "current": "73.4 tahun (2024)", "five_year_projection": "74.8 tahun (2029)", "insight": "Negara berkembang menutup gap. Indonesia: 72 → 74 tahun.", "source": "ourworldindata.org/life-expectancy"},
    {"topic": "Renewable Energy Share", "current": "30% listrik global", "five_year_projection": "42% (2030 IEA estimate)", "insight": "Solar PV tumbuh eksponensial; harga turun 90% sejak 2010.", "source": "ourworldindata.org/renewable-energy"},
    {"topic": "AI Compute Growth", "current": "10^25 FLOPs frontier model (2024)", "five_year_projection": "10^28 FLOPs (2029)", "insight": "Compute training meningkat ~4x/tahun. Bottleneck: energy & GPU supply.", "source": "ourworldindata.org/artificial-intelligence"},
    {"topic": "Global Internet Users", "current": "5.5 miliar (2024)", "five_year_projection": "6.5 miliar (2029)", "insight": "Penetrasi terus naik di Afrika & Asia Selatan.", "source": "ourworldindata.org/internet"},
    {"topic": "Extreme Poverty Rate", "current": "8.5% populasi global", "five_year_projection": "6.5% (2029)", "insight": "Tren turun walau melambat post-COVID. Sub-Sahara Africa fokus.", "source": "ourworldindata.org/extreme-poverty"},
    {"topic": "Global CO₂ Emissions", "current": "37.4 GtCO₂ (2024)", "five_year_projection": "Plateau ~37 Gt (2029)", "insight": "Peak diharapkan akhir 2020s. Tergantung kebijakan & EV adoption.", "source": "ourworldindata.org/co2-emissions"},
    {"topic": "Median Age Population", "current": "30.9 tahun (global)", "five_year_projection": "32.2 tahun (2029)", "insight": "Aging society — peluang silver economy & healthcare.", "source": "ourworldindata.org/age-structure"},
    {"topic": "Electric Vehicle Sales Share", "current": "18% new car sales (2024)", "five_year_projection": "45% (2029)", "insight": "China memimpin. Indonesia EV adoption growing dari basis rendah.", "source": "ourworldindata.org/electric-car-sales"},
]

# ============ FREELANCE TIPS (static seed; AI can elaborate) ============
PORTFOLIO_TIPS = {
    "scholarship": [
        "Bangun narasi 'why you' yang spesifik dan otentik — jangan generik.",
        "Tunjukkan impact terukur (angka, KPI) di tiap project sebelumnya.",
        "Tiga pilar wajib: Leadership, Community Impact, Academic/Professional Excellence.",
        "Mintakan rekomendasi dari supervisor yang kenal Anda mendalam, bukan hanya jabatannya tinggi.",
        "Latihan IELTS minimal 6 bulan sebelum deadline — target di atas requirement.",
    ],
    "job": [
        "Sesuaikan CV ke setiap perusahaan — gunakan kata kunci dari job description.",
        "Buat 'STAR stories' (Situation–Task–Action–Result) untuk top 8 prestasi Anda.",
        "Bangun online presence: LinkedIn rapi, portfolio website, kontribusi open source jika tech.",
        "Network: 70% lowongan terbaik tidak pernah di-publish. Reach out alumni & employees.",
        "Latihan mock interview dengan teman atau platform seperti Pramp / interviewing.io.",
    ],
    "freelance": [
        "Spesialisasi > generalist. Pilih 1 niche yang Anda kuasai dan brand di sana.",
        "Pricing tier: starter, standard, premium — jangan jual murah di awal, malah jangka panjang merugikan.",
        "Bangun case study lengkap (problem → process → result) di portfolio website pribadi.",
        "Testimoni & social proof: minta review setiap selesai project.",
        "Investasi waktu di 1 platform dulu (misal Upwork), kuasai algoritma & rating-nya.",
    ],
}
